
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author martin
 */
public class Principal extends javax.swing.JFrame {
    Graphics gpsMiDibu;
    Point coord;//point es un objeto, que guarda coordenadas
    Point ini;
    
    //int X1, X2;
    //int Y1, Y2;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();//metodo para construir las cosas, instancia las cosas
        gpsMiDibu = cnvDibu.getGraphics();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFigura = new javax.swing.JButton();
        cnvDibu = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFigura.setText("Cerrar la figura");
        btnFigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiguraActionPerformed(evt);
            }
        });
        getContentPane().add(btnFigura, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        cnvDibu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnvDibuMouseClicked(evt);
            }
        });
        getContentPane().add(cnvDibu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 435));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnvDibuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnvDibuMouseClicked
        // TODO add your handling code here:
        //cnvDibu.getGraphics();//graphics dentro del canvas es el que modificamos
        /*if(X1 == 0 && Y1 == 0){
        X1 = evt.getX();
        Y1 = evt.getY();
        X2=X1;
        Y2=Y1;
        gpsMiDibu.fillOval(evt.getX() - 2, evt.getY() - 2, 4, 4);//-2 porque es la mitad del circulo
        }else{
        gpsMiDibu.fillOval(evt.getX() - 2, evt.getY() - 2, 4, 4);
        gpsMiDibu.drawLine(X2, Y2, evt.getX(),evt.getY());//x1,y1,x2,y2
        X2 = evt.getX();
        Y2 = evt.getY();
        }*/
        
        gpsMiDibu.setColor(Color.red);
        gpsMiDibu.fillOval(evt.getX() - 2, evt.getY() - 2, 4, 4);
        
        //ini.x = evt.getX();
        //ini.y = evt.getY();
        
        if(coord!=null){
            gpsMiDibu.drawLine(coord.x, coord.y, evt.getX(), evt.getY());
            coord.x = evt.getX();
            coord.y = evt.getY();
        }else {
            coord = new Point(evt.getX(),evt.getY());
            ini = new Point(evt.getX(),evt.getY());
            ini.x = evt.getX();
            ini.y = evt.getY();
        }
    }//GEN-LAST:event_cnvDibuMouseClicked

    private void btnFiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiguraActionPerformed
        /*gpsMiDibu.drawLine(X2, Y2, X1,Y1);
        X1 = 0;
        Y1 = 0;
        X2 = 0;
        Y2 = 0;
        */
        
        gpsMiDibu.drawLine(ini.x, ini.y, coord.x, coord.y);
        coord = null;
        ini = null;
    }//GEN-LAST:event_btnFiguraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {//hilos de ejecucion, ejecutar multitarea
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFigura;
    private java.awt.Canvas cnvDibu;
    // End of variables declaration//GEN-END:variables
}
